print(100+50)
print("100 + 50")
print("Hola Mundo 'Me gusta estudiar Python' en mi pc")
hola = 100
hola2 = 50
print(hola + hola2)
print("Hola " + 'Melvin')
print("Hola" + " Melvin")
print("Hola" + " " + "Melvin")
print("Me llamo \"Melvin\"")
print("Esta es una linea\nY esta es otra linea")
print("\t Esta es una tercer linea con tabulacion")
print('This isn\'t a number')
print("Este signo \\ es una barra invertida")
print("A\tB\tC\nD\tE\tF\nG\tH\tI")
print("Barra Normal: /")
print("Barra Invertida: \\")
print("Poner comillas dobles en un texto \"n\"")

# input
print("nombre completo del usuario: " + input("Escribe tu nombre: ") + " " + input("Escribe tu apellido: "))
print(input("Escribe tu nombre: "))
print(input("Escribe tu apellido: "))
print(input("¿Qué estás estudiando? "))
print("Tu nombres y apellido es: " + input("dime tu nombre:" ) + " " + input("dime tu apellidos: "))
print(input("Dime tu nombre: "))
print("Tu nombre es: " + input("Dime tu nombre: "))
print("Tu apellido es: " + input("Dime tu apellido: "))
print("Tu nombre es: " + input("Dime tu nombre: ") + " " + input("Dime tu apellidO: "))
print("Tu nombre y apellido es: " + input("Dime tu nombre: ") + " " +input("Dime tu apellido: "))
